del /a/f/q/s ".\*.o"
del /a/f/q/s ".\*.d"
del /a/f/q/s ".\*.axf"
del /a/f/q/s ".\*.bin.asm"
del /a/f/q/s ".\*.bin"
del /a/f/q/s ".\*._2i"
del /a/f/q/s ".\*.iex"
del /a/f/q/s ".\*.fed"
del /a/f/q/s ".\*.l2p"
del /a/f/q/s ".\*.icf"
del /a/f/q/s ".\*.__i"
del /a/f/q/s ".\*.__i"
del /a/f/q/s ".\*.crf"
del /a/f/q/s ".\*.map"
del /a/f/q/s ".\*.dep"
del /a/f/q/s ".\*.htm"
del /a/f/q/s ".\*.lnp"
del /a/f/q/s ".\JLinkLog.txt"
del /a/f/q/s ".\JLinkSettings.ini"

del /a/f/q/s ".\*.uvguix.*"
:del /a/f/q/s ".\*.uvoptx.*"
pause