#ifndef _JUMA_ERROR_CODE_H_
#define _JUMA_ERROR_CODE_H_

//////////////////////JUMA_ERROR_CODE////////////////////

#define JUMA_ERROR_CODE_SUCCEED                        0x00000000UL

//FUNCTION POINT NULL
#define JUMA_ERROR_CODE_FUNCTION_POINT_NULL            0x00000001UL

//RES BUSY
#define JUMA_ERROR_CODE_SYS_RES_TIMER1_BUSY            0x40009000UL
#define JUMA_ERROR_CODE_SYS_RES_TIMER2_BUSY            0x4000A000UL


//BLE_INFRARED
#define JUMA_ERROR_CODE_INFRARED_CURRENT_SENDING       0x80000000UL
#define JUMA_ERROR_CODE_INFRARED_CURRENT_NO_CONFIG     0x80000001UL

#endif  //JUMA_ERROR_CODE
